inference_engine2/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from inference2 import views
from inference_engine2 import settings

urlpatterns = [

    url(r'^version1/$', views.version1_view, name='version1'),
    url(r'^version1/test_machine/$', views.try_input, name='version1_try_input'),
    url(r'^versions/$', views.version_view, name='versions'),
    url(r'^versions/(?P<version>[0-9]+)/details/$', views.version_details, name='version_details'),
    url(r'^version/(?P<version_item>[0-9]+)/dictionary/$', views.version_dictionary, name='version_dictionary'),
    url(r'^version/(?P<version_item>[0-9]+)/alphabetical/list/$', views.version_alphabetical, name='version_alphabetical'),
    url(r'^version/(?P<version_item>[0-9]+)/categorical/list/$', views.version_categorical, name='version_categorical'),
    url(r'^version/(?P<version_item>[0-9]+)/try/input/$', views.version_try_input, name='version_try_input'),

    url(r'^version1/dictionary$', views.dictionary, name='dict-result'),
    url(r'^tested_dictionary$', views.tested_dict, name='result'),
    url(r'^prove$', views.prove, name='prove'),
    url(r'^export_xlsx/(?P<archives_id>[0-9]+)$',
        views.export_xlsx, name='export_xlsx'),
    url(r'^progress$', views.progress, name='progress'),
    url(r'^archives$', views.archives, name='archives'),
    url(r'^files$', views.download_files, name='archives'),
    url(r'^archives/(?P<num>[0-9]+)$',
        views.assign_archives, name='assign_archives'),
    url(r'^archives/(?P<num>[0-9]+)/(?P<type>[a-z]+)$',
        views.assign_archives, name='assign_archives_type'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^getdict$', views.getdict, name='getdict'),
    url(r'^author', views.author, name='author'),
    url(r'^tested_dict', views.tested_dictionary, name='tested_dictionary'),


    url(r'^$', views.try_input, name='try_input'),
    url(r'^clear_output', views.clear_output, name='clear_output'),
    url(r'^clear', views.clear, name='clear-result'),

]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inference2/models.py
from django.db import models


# Create your models here.


class InstructionFile(models.Model):
    name = models.CharField(max_length=100, default='name')
    data = models.FileField(upload_to='./static/inference2/')

    PDF = 'pdf'
    CSV = 'csv'
    FILE_EXTENSION = ((PDF, 'Pdf'), (CSV, 'Csv'))
    FILE_TYPE_CHOICES = (
        ('0', 'rules_in_depth'),
        ('1', 'download_dictionary'),
        ('2', 'rules_in_brief'),
        ('3', 'arguments'),
    )
    COLOR_CHOICES = (
        ('red', 'red'),
        ('green', 'green'),
        ('blue', 'blue'),
        ('white', 'white'),
    )
    file_type = models.CharField(
        max_length=1, choices=FILE_TYPE_CHOICES, default='0')
    color_type = models.CharField(
        max_length=10, choices=COLOR_CHOICES, default='white')

    file_extension = models.CharField(max_length=20, choices=FILE_EXTENSION, default='PDF')

    def save(self, *args, **kwargs):
        super(InstructionFile, self).save(*args, **kwargs)
        filename = self.data.url


class Archives(models.Model):
    archives_date = models.DateField()
    algorithm = models.CharField(max_length=300, blank=False, null=False)
    dictionary = models.CharField(max_length=300, blank=False, null=False, default='')
    test_machine = models.CharField(max_length=300, blank=False, null=False, default='')

    def __unicode__(self):
        return u'{0}, {1}'.format(self.archives_date, self.algorithm)

    def __str__(self):
        return u'{0}, {1}'.format(self.archives_date, self.algorithm)

    class Meta:
        managed = True
        db_table = 'archives'


class Define3Notes(models.Model):
    notes = models.TextField()

    def __str__(self):
        return u'{0}'.format(self.id)


class Define3(models.Model):
    extra = models.CharField(max_length=1000, blank=True, null=True)
    type = models.CharField(max_length=1000, blank=True, null=True)
    word = models.CharField(max_length=1000, blank=True, null=True)
    rel = models.CharField(max_length=1000, blank=True, null=True)
    definition = models.CharField(max_length=1000, blank=True, null=True)
    subject = models.CharField(max_length=1000, blank=True, null=True)
    def_object = models.CharField(max_length=1000, blank=True, null=True)
    archives = models.ForeignKey(Archives, on_delete=models.CASCADE)
    version = models.ForeignKey('Version', null=True, blank=True)

    class Meta:
        managed = True
        db_table = 'define3'


class TestedDictionary(models.Model):
    extra = models.CharField(max_length=1000, blank=True, null=True)
    type = models.CharField(max_length=1000, blank=True, null=True)
    word = models.CharField(max_length=1000, blank=True, null=True)
    rel = models.CharField(max_length=1000, blank=True, null=True)
    definition = models.CharField(max_length=1000, blank=True, null=True)
    subject = models.CharField(max_length=1000, blank=True, null=True)
    def_object = models.CharField(max_length=1000, blank=True, null=True)
    archives = models.ForeignKey(Archives, on_delete=models.CASCADE)

    class Meta:
        managed = True
        db_table = 'testeddict'


class Input(models.Model):
    col1 = models.CharField(max_length=5, blank=True, null=True)
    col2 = models.CharField(max_length=1000, blank=True, null=True)
    col3 = models.CharField(max_length=300, blank=True, null=True)
    archives = models.ForeignKey(Archives, on_delete=models.CASCADE)

    class Meta:
        managed = True
        db_table = 'input'


class Output(models.Model):
    col1 = models.CharField(max_length=200, blank=True, null=True)
    col2 = models.CharField(max_length=1000, blank=True, null=True)
    col3 = models.CharField(max_length=300, blank=True, null=True)
    archives = models.ForeignKey(Archives)

    class Meta:
        managed = True
        db_table = 'output'
        verbose_name = "Argument"
        verbose_name_plural = "Arguments"

    def __str__(self):
        return u'{0}'.format(self.id)


class Algorithm(models.Model):
    def validate_file_extension(value):
        from django.core.exceptions import ValidationError
        if not value.name.endswith('.py'):
            raise ValidationError(
                u'Only files with py extenstion are supported.')

    name = models.CharField(max_length=200)
    notes = models.TextField(null=True, blank=True)
    try_input_notes = models.TextField(null=True, blank=True, default='')
    data = models.FileField(upload_to='./inference2/Proofs/', validators=[])
    test_machine = models.FileField(upload_to='./inference2/Proofs/', validators=[], null=True, blank=True,
                                    default=None)
    dictionary = models.FileField(upload_to='./inference2/Proofs/', validators=[], null=True, blank=True, default=None)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        super(Algorithm, self).save(*args, **kwargs)


class Profile(models.Model):
    name = models.CharField(max_length=200)
    about = models.TextField()
    hobbies = models.CharField(max_length=500, null=True, blank=True)
    skills = models.CharField(max_length=500, null=True, blank=True)
    facebook = models.CharField(max_length=200, null=True, blank=True)
    twitter = models.CharField(max_length=200, null=True, blank=True)
    instagram = models.CharField(max_length=200, null=True, blank=True)
    profile_photo = models.ImageField(upload_to='img', null=True, blank=True, default=None)

    def __str__(self):
        return u'{0}'.format(self.id)


class Settings(models.Model):
    rows_to_show = models.IntegerField(default=40000)

    def __str__(self):
        return u'{0}'.format(self.id)

    class Meta:
        verbose_name_plural = "Settings"


class VersionItem(models.Model):
    DOWNLOADABLE_DICT = 'downloadable_dictionary'
    EXPLANATION = 'explanation'
    ALPHABETIC_WORD_LIST = 'alphabetic'
    CATEGORIZED_WORD_LIST = 'categorize'
    DICTIONARY = 'dictionary'
    TEST_MACHINE = 'test_machine'

    ITEM_CHOICES = ((DOWNLOADABLE_DICT, 'Download Dict'),
                    (EXPLANATION, 'Explanation'),
                    (ALPHABETIC_WORD_LIST, 'Alphabetical Word List'),
                    (CATEGORIZED_WORD_LIST, 'Categorized Word List'),
                    (DICTIONARY, 'Dictionary'),
                    (TEST_MACHINE, 'Test Machine'),
                    )

    title = models.CharField(max_length=50)
    item_category = models.CharField(max_length=50, choices=ITEM_CHOICES, default=DICTIONARY)
    version = models.ForeignKey('Version', null=True, blank=True)
    code_file_name = models.CharField(max_length=50, null=True, blank=True)
    notes = models.TextField(default='')
    explanation_file = models.FileField(upload_to='./static/inference2/', null=True, blank=True)

    class Meta:
        unique_together = ('version', 'item_category')

    def __str__(self):
        return self.title


class Version(models.Model):
    title = models.CharField(max_length=50, unique=True)
    active = models.BooleanField(default=False)
    version_directory = models.CharField(max_length=50, default='version1')

    def __str__(self):
        return self.title

inference2/forms.py
import csv

from django.db import transaction
from django import forms
from django.forms.forms import NON_FIELD_ERRORS
from django.utils import six
from django.utils.translation import ugettext_lazy as _
from inference2.models import Archives, Define3

from django.forms import ModelChoiceField


class CSVImportError(Exception):
    pass


class ImportCSVForm(forms.Form):
    csv_file = forms.FileField(required=True, label=_('CSV File'))
    has_headers = forms.BooleanField(
        label=_('Has headers'),
        help_text=_('Check this if your CSV file '
                    'has a row with column headers.'),
        initial=True,
        required=False,
    )
    archives = forms.ModelChoiceField(
        queryset=Archives.objects.all(),
        label=_('Select for Archives'),
        required=False,
        help_text=_('Create Archives if it is not here.'),
    )
    archives_check = forms.BooleanField(
        label=_('Check for Old Archives'),
        help_text=_('UnCheck this if your Definition has to replace '
                    'the old entries of same archive date.'),
        initial=True,
        required=False,
    )

    def __init__(self, *args, **kwargs):
        self.importer_class = kwargs.pop('importer_class')
        self.dialect = kwargs.pop('dialect')
        super(ImportCSVForm, self).__init__(*args, **kwargs)
        self.fields['csv_file'].help_text = "Expected fields: {}".format(
            self.expected_fields)

    # def clean_csv_file(self):
    #     if six.PY3:
    #         # DictReader expects a str, not bytes in Python 3.
    #         csv_text = self.cleaned_data['csv_file'].read()
    #         csv_decoded = six.StringIO(csv_text.decode('utf-8'))
    #         print(csv_decoded)
    #         return csv_decoded
    #     else:
    #         return self.cleaned_data['csv_file']

    @property
    def expected_fields(self):
        fields = self.importer_class._meta.fields
        return ', '.join(fields)

    @transaction.atomic
    def import_csv(self):
        try:
            # print(self.cleaned_data['csv_file'])
            data = str(self.cleaned_data['csv_file'].read())
            lines = data.split('\\n')
            if len(lines) < 3:
                lines = data.split('\\r')
            reader = []
            fieldnames = self.importer_class.Meta.fields
            for line in lines:
                words = line.replace('"', '').replace("\\'", "'").split(',')
                temp = {}
                for index, value in enumerate(fieldnames):
                    try:
                        temp[value] = words[index]
                    except IndexError:
                        pass

                reader.append(temp)
            # reader =
            # reader = csv.DictReader(
            #     self.cleaned_data['csv_file'],
            #     fieldnames=self.importer_class.Meta.fields,
            #     dialect=self.dialect,
            # )
            print(reader)
            reader_iter = enumerate(reader, 1)
            archives_id = -1  # No Archives
            if self.cleaned_data['has_headers']:
                six.advance_iterator(reader_iter)
            if self.cleaned_data['archives']:
                archives_id = self.cleaned_data['archives'].id
            old_archives = self.importer_class.Meta.model.objects.filter(
                id=archives_id)
            if old_archives:
                # if self.cleaned_data['archives_check']:
                #     self.append_import_error(_("Defination already exist for this archives."))
                #     raise CSVImportError()
                # else:
                old_archives.delete()
            self.process_csv(reader_iter, archives_id)
            if not self.is_valid():
                raise CSVImportError()  # Abort the transaction
        except csv.Error:
            self.append_import_error(_("Bad CSV format"))
            raise CSVImportError()

    def process_csv(self, reader, archives_id=-1):
        list_obj = []
        for i, row in reader:
            # if not row.get('definition') and 'definition' in self.importer_class.Meta.fields:
            #     # SKIP empty rows
            #     continue
            if archives_id != -1:
                row['archives'] = archives_id
            row_result = self.process_row(i, row)
            if row_result:
                list_obj.append(row_result)

                # if list_obj:
                #     list_obj[0].__class__.objects.bulk_create(
                #         list_obj, batch_size=len(list_obj))

    def append_import_error(self, error, rownumber=None, column_name=None):
        if rownumber is not None:
            if column_name is not None:
                # Translators: "{row}", "{column}" and "{error}"
                # should not be translated
                fmt = _("Could not import row #{row}: {column} - {error}")
            else:
                # Translators: "{row}" and "{error}" should not be translated
                fmt = _("Could not import row #{row}: {error}")
        else:
            if column_name is not None:
                raise ValueError("Cannot raise a CSV import error on a specific "
                                 "column with no row number.")
            else:
                # Translators: "{error}" should not be translated
                fmt = _("Could not import the CSV document: {error}")

        if NON_FIELD_ERRORS not in self._errors:
            self._errors[NON_FIELD_ERRORS] = self.error_class()
        self._errors[NON_FIELD_ERRORS].append(
            fmt.format(error=error, row=rownumber, column=column_name))

    def process_row(self, i, row):
        importer = self.importer_class(data=row)
        if importer.is_valid():
            return importer.save(commit=True)
        else:
            for error in importer.non_field_errors():
                self.append_import_error(rownumber=i, error=error)
            for field in importer:
                for error in field.errors:
                    self.append_import_error(rownumber=i, column_name=field.label,
                                             error=error)
            return None

inference2/templates/inference2/archives.html
{% extends "base.html" %}
{% load extra_tags %}

{% block content %}
    <h1>Archives</h1>

    <table class="table table-bordered">
        <thead>
          <tr>
                <th>Date</th>
                <th>Algorithm</th>
          </tr>
        </thead>
        <tbody>
        {% for row in result %}
			<tr>
			    <td><a href="archives/{{row.id}}">{{ row.archives_date | date:"M d, Y" }}</a></td>
			    <td><a href="archives/{{row.id}}">{{row.algorithm}}</a></td>
			</tr>
		{% endfor %}
        </tbody>
    </table>
{% endblock content %}

inference2/templates/inference2/author.html
{% extends "base.html" %}
{% load extra_tags %}

{% block content %}

    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
    <div class="container">
        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-10">

                <div class="profile">
                    <div class="col-md-3">
                        <img src="{{ profile.profile_photo.url }}" style="width: 100%;height: 100%;">
                    </div>
                    <div class="col-md-9">

                            <h2>{{ profile.name }}</h2>
                            <p><strong>About: </strong> {{ profile.about }} </p>
{#                            <p><strong>Hobbies: </strong> {{ profile.hobbies }} </p>#}
{#                            <p><strong>Skills: </strong>{{ profile.skills }}</p>#}

                    </div>
{#                    <div class="col-xs-12 divider text-center">#}
{#                        <div class="col-xs-12 col-sm-4 emphasis">#}
{##}
{#                            <button class="btn btn-success btn-block"><span class="fa fa-plus-circle"></span> Follow#}
{#                            </button>#}
{#                        </div>#}
{#                        <div class="col-xs-12 col-sm-4 emphasis">#}
{#                            <button class="btn btn-info btn-block"><span class="fa fa-user"></span> View Profile#}
{#                            </button>#}
{#                        </div>#}
{#                        <div class="col-xs-12 col-sm-4 emphasis">#}
{#                            <div class="btn-group dropup btn-block">#}
{#                                <button type="button" class="btn btn-primary"><span class="fa fa-gear"></span> Options#}
{#                                </button>#}
{#                                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">#}
{#                                    <span class="caret"></span>#}
{#                                    <span class="sr-only">Toggle Dropdown</span>#}
{#                                </button>#}
{#                                <ul class="dropdown-menu text-left" role="menu">#}
{#                                    <li><a href="mailto:kylefoley202@gmail.com?Subject=Query%20Logical%20Machine"#}
{#                                           target="_top"> <span class="fa fa-envelope pull-right"></span> Send an email#}
{#                                    </a></li>#}
{#                                </ul>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
                </div>
            </div>
            <div class="col-md-1"></div>


            </div>
        </div>
    </div>
{% endblock content %}

inference2/templates/inference2/dict.html
{% extends "base.html" %}
{% load extra_tags %}

{% block content %}


    <h1>
    {% if tested_dict %}
        Tested Dictionary
    {% else %}
        Dictionary
    {% endif %}
    </h1>
    <br>
    {% if notes %}
        <textarea rows="4" cols="100" readonly>{{ notes }}</textarea>
    {% endif %}


    <br>

    <table class="table table-bordered">
        <thead class="thead-inverse">
        <tr>
            <th style="width:5%">Type</th>
            <th style="width:5%">Word</th>
            <th style="width:10%">Relation</th>
            <th style="width:65%">Definition</th>
            <th style="width:5%">superscript</th>
            <th style="width:5%">subject</th>
            <th style="width:5%">object</th>

        </tr>
        </thead>
        <tbody>
        {% for sentense in output %}
            <tr>
                <td>{{ sentense.extra }}</td>
                <td>{{ sentense.type }}</td>
                <td>{{ sentense.word }}</td>
                <td>{{ sentense.rel }}</td>
                <td>{{ sentense.definition }}</td>
                <td>{{ sentense.subject }}</td>
                <td>{{ sentense.def_object }}</td>

            </tr>

        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

inference2/templates/inference2/files.html
{% extends "base.html" %}
{% load extra_tags %}

{% block content %}
    <h1>Download Files</h1>

    <table class="table table-bordered">
        <thead>
          <tr>
                <th>Name</th>
                <th>Link</th>
          </tr>
        </thead>
        <tbody>
        {% for row in ins_files %}
			<tr style="background:{{ row.color_type }} ">
			    <td>{{ row.name }}</td>
			    <td><a href="{{ row.data }}">Download</a></td>
			</tr>
		{% endfor %}
        </tbody>
    </table>
{% endblock content %}

inference2/templates/inference2/files_in_brief.html
{% extends "base.html" %}
{% load extra_tags %}

{% block content %}
    <h1>Download Files</h1>

    <table class="table table-bordered">
        <thead>
          <tr>
                <th>Name</th>
                <th>Link</th>
          </tr>
        </thead>
        <tbody>
        {% for row in ins_files %}
			<tr style="background:{{ row.color_type }} ">
			    <td>{{ row.name }}</td>
			    <td><a href="{{ row.data }}">Download</a></td>
			</tr>
		{% endfor %}
        </tbody>
    </table>
{% endblock content %}

inference2/templates/inference2/tested_dict.html
{% extends "base.html" %}
{% load extra_tags %}


{% block content %}
    <h1>Tested Dictionary</h1>

<table border="1">

{% for row in result %}
    <tr>
        <td>{{ row.0 }}</td>
        <td>{{ row.1 }}</td>
        <td>{{ row.2 }}</td>
        <td>{{ row.3 }}</td>
        <td>{{ row.4 }}</td>
        <td>{{ row.5 }}</td>
        <td>{{ row.6 }}</td>
        <td>{{ row.7 }}</td>

    </tr>
{% endfor %}

</table>
{% endblock content %}

inference2/templates/inference2/version_alphabetical.html
{% extends "base.html" %}
{% load extra_tags %}

{% block content %}

    <a class="btn btn-primary"
       href="{% url 'versions' %}">Home</a>
    {% if version_cat_item %}
        <a class="btn btn-primary"
           href="{% url 'version_categorical' version_cat_item.id %}">{{ version_cat_item.title }}</a>
    {% endif %}

    <h1>
        Dictionary
    </h1>
    <br>
    {% if version_item.notes %}
        <textarea rows="4" cols="100" readonly>{{ version_item.notes }}</textarea>
    {% endif %}


    <br>

    <table class="table table-bordered">
        <thead class="thead-inverse">
        <tr>
            <th style="width:5%">Word</th>
            <th style="width:5%">Notes</th>
        </tr>
        </thead>
        <tbody>
        {% for sentense in output %}
            <tr>
                <td>{{ sentense.type }}</td>
                <td>{{ sentense.rel }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

inference2/templates/inference2/version_categorical.html
{% extends "base.html" %}
{% load extra_tags %}

{% block content %}

    <a class="btn btn-primary"
       href="{% url 'versions' %}">Home</a>
    {% if version_alp_item %}
        <a class="btn btn-primary"
           href="{% url 'version_alphabetical' version_alp_item.id %}">{{ version_alp_item.title }}</a>
    {% endif %}


    <h1>
        Dictionary
    </h1>
    <br>
    {% if version_item.notes %}
        <textarea rows="4" cols="100" readonly>{{ version_item.notes }}</textarea>
    {% endif %}


    <br>

    <table class="table table-bordered">
        <thead class="thead-inverse">
        <tr>
            <th style="width:5%">Type</th>
            <th style="width:5%">Word</th>
            <th style="width:10%">Relation</th>
            <th style="width:65%">Definition</th>
            <th style="width:5%">superscript</th>
            <th style="width:5%">subject</th>
            <th style="width:5%">object</th>

        </tr>
        </thead>
        <tbody>
        {% for sentense in output %}
            <tr>
                <td>{{ sentense.extra }}</td>
                <td>{{ sentense.type }}</td>
                <td>{{ sentense.word }}</td>
                <td>{{ sentense.rel }}</td>
                <td>{{ sentense.definition }}</td>
                <td>{{ sentense.subject }}</td>
                <td>{{ sentense.def_object }}</td>

            </tr>

        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

inference2/templates/inference2/version_details.html
{% extends "base.html" %}
{% load extra_tags %}

{% block base_head %}
    <script type="text/javascript">
        $(document).ready(function () {

        });
    </script>
{% endblock base_head %}

{% block content %}
    {% for version_item in version.versionitem_set.all %}
        {% if version_item.item_category ==  'dictionary' %}
            <a class="btn btn-primary"
               href="{% url 'version_dictionary' version_item.id %}">{{ version_item.title }}</a>

        {% elif version_item.item_category ==  'explanation' or version_item.item_category == 'downloadable_dictionary' %}
            <a class="btn btn-primary" href="{{ version_item.explanation_file.url }}"
               target="_blank">{{ version_item.title }}</a>

        {% elif version_item.item_category ==  'alphabetic' %}
            <a class="btn btn-primary"
               href="{% url 'version_alphabetical' version_item.id %}">{{ version_item.title }}</a>
        {% elif version_item.item_category ==  'categorize' %}
            <a class="btn btn-primary"
               href="{% url 'version_categorical' version_item.id %}">{{ version_item.title }}</a>

        {% elif version_item.item_category ==  'test_machine' %}
            <a class="btn btn-primary"
               href="{% url 'version_try_input' version_item.id %}">{{ version_item.title }}</a>
        {% else %}
            <a class="btn btn-primary" href="#">{{ version_item.title }}</a>
        {% endif %}
    {% endfor %}
{% endblock content %}

inference2/templates/inference2/version_dict.html
{% extends "base.html" %}
{% load extra_tags %}

{% block content %}


    <h1>
        Dictionary
    </h1>
    <br>
    {% if version_item.notes %}
        <textarea rows="4" cols="100" readonly>{{ version_item.notes }}</textarea>
    {% endif %}


    <br>

    <table class="table table-bordered">
        <thead class="thead-inverse">
        <tr>
            <th style="width:5%">Type</th>
            <th style="width:5%">Word</th>
            <th style="width:10%">Relation</th>
            <th style="width:65%">Definition</th>
            <th style="width:5%">superscript</th>
            <th style="width:5%">subject</th>
            <th style="width:5%">object</th>

        </tr>
        </thead>
        <tbody>
        {% for sentense in output %}
            <tr>
                <td>{{ sentense.extra }}</td>
                <td>{{ sentense.type }}</td>
                <td>{{ sentense.word }}</td>
                <td>{{ sentense.rel }}</td>
                <td>{{ sentense.definition }}</td>
                <td>{{ sentense.subject }}</td>
                <td>{{ sentense.def_object }}</td>

            </tr>

        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

inference2/templates/inference2/versions_page.html
{% extends "base.html" %}
{% load extra_tags %}

{% block base_head %}
    <script type="text/javascript">
        $(document).ready(function () {

        });
    </script>
{% endblock base_head %}

{% block content %}

    {% for version in versions %}
        <a class="btn btn-primary" href="{% url 'version_details' version.id %}">{{ version.title }}</a>
    {% endfor %}
{% endblock content %}